name: "Generate Single Header"

on:
  push:
    branches: [main]

jobs:
  run:
    name: Generate
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.25.1"

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_DEMO=OFF -DBUILD_SINGLE_HEADER=ON

      - name: Build
        working-directory: build
        run: cmake --build . -j$(nproc)

      - name: Collect all headers into one file
        run: |
          chmod +x ${{github.workspace}}/scripts/generate_venus_header.sh
          ${{github.workspace}}/scripts/generate_venus_header.sh > ${{github.workspace}}/core/venus.hpp

      - name: Run
        working-directory: ${{github.workspace}}/build
        run: |
          ./scripts/make_single_header ${{github.workspace}}/core/venus.hpp ${{github.workspace}}/single_include/venus.hpp

      - name: Upload
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update single header with latest code
          file_pattern: |
            single_include/*
            core/venus.hpp
          commit_user_name: GitHub Actions Bot
          commit_user_email: action@github.com
          commit_options: "--allow-empty"
